name: Terraform Destroy
on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    # This step saves your AWS access and secret key to be used by Terraform
    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.13.4
    - name: Terraform Init
      run: terraform init  
  # - name: Show Destroy plan
  #   run: terraform plan -destroy
  #     # continue-on-error: true
    - name: Terraform destroy
      run: terraform destroy -auto-approve 